import { PrismaClient } from '@prisma/client';
import { v4 as uuidv4 } from 'uuid';

const prisma = new PrismaClient();

// Define categories with generated UUIDs
const demoCategories = [
  { id: uuidv4(), name: "Blegtoria" },
  { id: uuidv4(), name: "Mjetet" },
  { id: uuidv4(), name: "Serat" },
  { id: uuidv4(), name: "Teknologjia" },
  { id: uuidv4(), name: "Magazinimi" },
  { id: uuidv4(), name: "FaraPerime" },
  { id: uuidv4(), name: "PlehraKimike" },
  { id: uuidv4(), name: "Pesticidet" },
  { id: uuidv4(), name: "Ujitje" },
  { id: uuidv4(), name: "Veshje" }
];

const demoProducts = [
  {
    id: "1",
    title: "Brokoli & Lulelaker / Domate / Karrota / Kunguj",
    price: 800,
    rating: 5,
    description: "(Pako 100 cope)",
    mainImage: "/img/f/vegetables.jpg",
    slug: "fara-perime-demo",
    manufacturer: "UBT AgroMarket",
    category: "FaraPerime",
    inStock: 1,
    unoptimized: true,
  },
  {
    id: "2",
    title: "Planterra 12-12-17+2MgO+TE 25kg",
    price: 2500,
    rating: 5,
    description: "Pleh kokrrizor me formulë të balancuar, për Pemë Frutore të ndryshme, Agrume, Perime, etj.",
    mainImage: "/img/f/planterra.jpg",
    slug: "planterra-f1-demo",
    manufacturer: "UBT AgroMarket",
    category: "PlehraKimike",
    inStock: 1,
    unoptimized: true,
  },
  {
    id: "3",
    title: "Fungicide / Insekticide / Herbicide",
    price: 2800,
    rating: 4,
    description: "Fungicide - Ridomil Gold, Dithane M-45 / Insekticide - Decis, Karate Zeon / Herbicide - Roundup",
    mainImage: "/img/f/pesticide.jpeg",
    slug: "pesticide-demo",
    manufacturer: "UBT AgroMarket",
    category: "Pesticidet",
    inStock: 1,
    unoptimized: true,
  },
  {
    id: "4",
    title: "Frezë Italiane CELLI, 310cm seria e rëndë",
    price: 1500000,
    rating: 5,
    description: "Frezë CELLI PIONEER 140 italiane, për traktorë 120-160 KF, gjerësi punuese 310 cm, thellësi 25 cm, kambio 4 shpejtësi, transmision me friksion, rul Packer Φ 470, peshë 1540 kg.",
    mainImage: "/img/f/freze.jpeg",
    slug: "freze-demo",
    manufacturer: "UBT AgroMarket",
    category: "Mjetet",
    inStock: 1,
    unoptimized: true,
  },
  {
    id: "5",
    title: "Dem Race Limousine për Mbarështim",
    price: 220000,
    rating: 5,
    description: "Dem Limousine, i shëndetshëm dhe me cilësi të lartë për mbarështim",
    mainImage: "/img/f/dem.jpg",
    slug: "dem-race-demo",
    manufacturer: "UBT AgroMarket",
    category: "Blegtoria",
    inStock: 1,
    unoptimized: true,
  },
  {
    id: "6",
    title: "Fare Misri PR32B10 nga gjigandi Pioneer",
    price: 4000,
    rating: 5,
    description: "Fare misri PR32B10 është një hibrid i bardhë me kapacitet të lartë prodhues, sistem rrënjor të fuqishëm dhe kokrra me përmbajtje të lartë proteinash, i përshtatshëm për terrene të ndryshme.",
    mainImage: "/img/f/misri.jpg",
    slug: "fare-misri-demo",
    manufacturer: "UBT AgroMarket",
    category: "FaraPerime",
    inStock: 1,
    unoptimized: true,
  },
  {
    id: "7",
    title: "Sere ne shitje",
    price: 5000,
    rating: 5,
    description: "5 USD për 200–499 metra katrorë, 4.5 USD për 500–799 metra katrorë, 4 USD për 800–999 metra katrorë, 3.8 USD për 1000–1999 metra katrorë, 3.5 USD për ≥2000 metra katrorë.",
    mainImage: "/img/f/sera.jpg",
    slug: "sera-demo",
    manufacturer: "UBT AgroMarket",
    category: "Serat",
    inStock: 1,
    unoptimized: true,
  },
  {
    id: "8",
    title: "Pompë Uji Centrifugale me Thithje Elektrike 20 Inç",
    price: 28000,
    rating: 5,
    description: "Pompa e ujit me thithje elektrike centrifugale 20 inç është një zgjidhje e fuqishme dhe efikase ujitëse e krijuar për aplikime bujqësore, duke siguruar rrjedhje të besueshme uji për sistemet e ujitjes në shkallë të gjerë.",
    mainImage: "/img/f/pompe.avif",
    slug: "pompe-uji-demo",
    manufacturer: "Bosch",
    category: "Ujitje",
    inStock: 1,
    unoptimized: true,
  },
  {
    id: "9",
    title: "Veshje",
    price: 1900,
    rating: 3,
    description: "Çizme të gjata rezistente ndaj ujit, të rehatshme dhe të përshtatshme për terrene të ndryshme dhe aktivitete në natyrë.",
    mainImage: "/img/f/cizme.webp",
    slug: "veshje-demo",
    manufacturer: "Monagri",
    category: "Veshje",
    inStock: 1,
    unoptimized: true,
  },
  {
    id: "10",
    title: "Ripe Robotics",
    price: 45000000,
    rating: 5,
    description: "Ripe Robotics është një robot autonom që grumbullon fruta në mënyrë efikase, duke përdorur inteligjencën artificiale për të optimizuar rendimentin dhe ulur kostot e punës.",
    mainImage: "/img/f/robot.jpg",
    slug: "ripe-robotics-demo",
    manufacturer: "Ripe Robotics",
    category: "Teknologjia",
    inStock: 1,
    unoptimized: true,
  },
  {
    id: "11",
    title: "Thermo King",
    price: 5200000,
    rating: 5,
    description: "This is notebook description",
    mainImage: "/img/f/frigorifer.jpg",
    slug: "thermo-king-demo",
    manufacturer: "Thermo King",
    category: "Magazinimi",
    inStock: 1,
    unoptimized: true,
  },

    {
      id: "12",
      title: "Lopë Holstein për Qumësht",
      price: 250000,
      rating: 4,
      description: "Lopë Holstein me prodhim të lartë qumështi (25-30 litra/ditë), e shëndetshme dhe e vaksinuar",
      mainImage: "/img/f/12.jpeg",
      slug: "lope-holstein-demo",
      manufacturer: "UBT AgroMarket",
      category: "Blegtoria",
      inStock: 1,
    },
    {
      id: "13",
      title: "Dhi Saanen për Qumësht",
      price: 80000,
      rating: 4,
      description: "Dhi Saanen me prodhim të lartë qumështi (4-6 litra/ditë), e përshtatshme për ferma të vogla",
      mainImage: "/img/f/13.jpeg",
      slug: "dhi-saanen-demo",
      manufacturer: "UBT AgroMarket",
      category: "Blegtoria",
      inStock: 1,
    },
    {
      id: "14",
      title: "Qengj Rrace Merino",
      price: 35000,
      rating: 5,
      description: "Qengj Merino me cilësi të lartë për mish dhe lesh, moshë 6-8 muaj",
      mainImage: "/img/f/14.jpg",
      slug: "qengj-merino-demo",
      manufacturer: "UBT AgroMarket",
      category: "Blegtoria",
      inStock: 1,
    },
    {
      id: "15",
      title: "Derri Landrace për Mbarështim",
      price: 60000,
      rating: 4,
      description: "Derri Landrace me gjenetikë të mirë për prodhim mish, moshë 4-6 muaj",
      mainImage: "/img/f/15.jpeg",
      slug: "derri-landrace-demo",
      manufacturer: "UBT AgroMarket",
      category: "Blegtoria",
      inStock: 1,
    },
    {
      id: "16",
      title: "Pulë Layer për Vezë",
      price: 1500,
      rating: 4,
      description: "Pulë layer me prodhim 280-300 vezë në vit, moshë 18-20 javë",
      mainImage: "/img/f/16.jpeg",
      slug: "pule-layer-demo",
      manufacturer: "UBT AgroMarket",
      category: "Blegtoria",
      inStock: 1,
    },
    {
      id: "17",
      title: "Gjel për Mbarështim",
      price: 4000,
      rating: 3,
      description: "Gjeli i shëndetshëm për mbarështim, moshë 8-10 muaj",
      mainImage: "/img/f/17.png",
      slug: "gjeli-mbarshtim-demo",
      manufacturer: "UBT AgroMarket",
      category: "Blegtoria",
      inStock: 1,
    },
    {
      id: "18",
      title: "Bletë Koloni për Mjaltë",
      price: 20000,
      rating: 5,
      description: "Koloni bletësh me krahinë të fortë, e përshtatshme për fillestarë",
      mainImage: "/img/f/18.jpeg",
      slug: "blete-koloni-demo",
      manufacturer: "UBT AgroMarket",
      category: "Blegtoria",
      inStock: 1,
    },
    {
      id: "19",
      title: "Kali Arab për Hipizëm",
      price: 500000,
      rating: 5,
      description: "Kali Arab i pastër racës, i trajnuar mirë për hipizëm dhe shfaqje",
      mainImage: "/img/f/19.webp",
      slug: "kali-arab-demo",
      manufacturer: "UBT AgroMarket",
      category: "Blegtoria",
      inStock: 1,
    },
    {
      id: "20",
      title: "Gomar",
      price: 80000,
      rating: 4,
      description: "Gomar i shëndetshëm dhe i fortë për transport në zonat malore",
      mainImage: "/img/f/20.jpg",
      slug: "gomar-transport-demo",
      manufacturer: "UBT AgroMarket",
      category: "Blegtoria",
      inStock: 1,
    },
    {
      id: "21",
      title: "Peshku Troftë për Pishinë",
      price: 10000,
      rating: 4,
      description: "Troftë e gjallë për pishina bujqësore, peshë 200-300g",
      mainImage: "/img/f/21.jpeg",
      slug: "trofte-peshkimi-demo",
      manufacturer: "UBT AgroMarket",
      category: "Blegtoria",
      inStock: 1,
    },

      {
        id: "22",
        title: "Traktor Farmtrac 6060 4WD",
        price: 4500000,
        rating: 5,
        description: "Traktor Farmtrac 6060 me 60 HP, 4WD, kabinë me kondicioner, sistem hidraulik me 3 pika, përshtatshëm për të gjitha llojet e punimeve bujqësore.",
        mainImage: "/img/f/22.jpg",
        slug: "traktor-farmtrac-demo",
        manufacturer: "Farmtrac",
        category: "Mjetet",
        inStock: 1,
      },
      {
        id: "23",
        title: "Autokombanje Claas Lexion 580",
        price: 25000000,
        rating: 5,
        description: "Pritëse gruri me kapacitet 15-20 ton/orë, sistem GPS, kabinë të rehatshme me klimë dhe monitorim kompjuterik të të gjitha funksioneve.",
        mainImage: "/img/f/23.jpg",
        slug: "priteze-claas-demo",
        manufacturer: "Claas",
        category: "Mjetet",
        inStock: 1,
      },
      {
        id: "24",
        title: "Pompë Ujitje 3HP",
        price: 25000,
        rating: 4,
        description: "Pompë centrifugale 3HP për ujitje, kapacitet 10m³/orë, presion 3 bar, e përshtatshme për kopshte dhe serra.",
        mainImage: "/img/f/24.jpg",
        slug: "pompe-ujitje-demo",
        manufacturer: "Pedrollo",
        category: "Mjetet",
        inStock: 1,
      },
      {
        id: "25",
        title: "Sharrë Diskore 2.5m",
        price: 650000,
        rating: 4,
        description: "Sharrë diskore 2.5 metra me 20 disqe, sistem hidraulik për rregullim të thellësisë, e përshtatshme për traktorë 80-100 HP.",
        mainImage: "/img/f/25.jpg",
        slug: "sharre-diskore-demo",
        manufacturer: "Kuhn",
        category: "Mjetet",
        inStock: 1,
      },
      {
        id: "26",
        title: "Mbledhëse Bari 1.8m",
        price: 420000,
        rating: 4,
        description: "Mbledhëse bari me gjerësi pune 1.8m, sistem automatik për formimin e baltukave, peshë 320kg.",
        mainImage: "/img/f/26.jpg",
        slug: "mbledhese-bari-demo",
        manufacturer: "John Deere",
        category: "Mjetet",
        inStock: 1,
      },
      {
        id: "27",
        title: "Pulverizator 600L",
        price: 780000,
        rating: 4,
        description: "Pulverizator 600 litra me pompë membranore, gjerësi pune 12m, sistem elektrik për kontrollin e presionit.",
        mainImage: "/img/f/27.jpeg",
        slug: "pulverizator-demo",
        manufacturer: "Berthoud",
        category: "Mjetet",
        inStock: 1,
      },
      {
        id: "28",
        title: "Kultivator 2.2m",
        price: 920000,
        rating: 5,
        description: "Kultivator 2.2 metra me 24 shpata, sistem hidraulik për transport, i përshtatshëm për traktorë 90-120 HP.",
        mainImage: "/img/f/28.jpg",
        slug: "kultivator-demo",
        manufacturer: "Maschio Gaspardo",
        category: "Mjetet",
        inStock: 1,
      },
      {
        id: "29",
        title: "Mbledhëse dengu",
        price: 1850000,
        rating: 4,
        description: "Presë balësh me kapacitet 120-150 balë/orë, sistem automatik për lidhjen e balëve, dimensione balësh 80x90 cm.",
        mainImage: "/img/f/29.jpeg",
        slug: "prese-balesh-demo",
        manufacturer: "New Holland",
        category: "Mjetet",
        inStock: 1,
      },
      {
        id: "30",
        title: "Shpërndarëse Drithërash 2000L",
        price: 1250000,
        rating: 5,
        description: "Shpërndarëse drithërash me kapacitet 2000 litra, sistem pneumatik për shpërndarje uniforme, pajisur me peshore dixhitale.",
        mainImage: "/img/f/30.jpeg",
        slug: "Shpërndarëse-drithi-demo",
        manufacturer: "Amazone",
        category: "Mjetet",
        inStock: 1,
      },
      {
        id: "31",
        title: "Makinë Patatesh",
        price: 3200000,
        rating: 4,
        description: "Makinë patatesh me sistem vibrimi për pastrim optimal, kapacitet 0.5-1 ha/orë, gjerësi pune 1.2m.",
        mainImage: "/img/f/31.jpg",
        slug: "makine-patate-demo",
        manufacturer: "Grimme",
        category: "Mjetet",
        inStock: 1,
      },

        {
          id: "32",
          title: "Sere Tunnel 6x30m",
          price: 320000,
          rating: 4,
          description: "Sere tunnel 6m gjerësi x 30m gjatësi, strukturë galvanizuese, mbulesë polietileni 200 micron me proteksion UV, përfshin sistem ventilimi dhe dritare anësore.",
          mainImage: "/img/f/32.jpg",
          slug: "sera-tunnel-demo",
          manufacturer: "UBT AgroMarket",
          category: "Serat",
          inStock: 1,
        },
        {
          id: "33",
          title: "Sere Multispan 8x40m",
          price: 1850000,
          rating: 5,
          description: "Sere profesionale multispan 8m x 40m, strukturë çeliku i galvanizuar, xhami të temperuar 4mm, sistem automatizimi ventilimi dhe hijezimi.",
          mainImage: "/img/f/33.jpeg",
          slug: "sera-multispan-demo",
          manufacturer: "UBT AgroMarket",
          category: "Serat",
          inStock: 1,
        },
        {
          id: "34",
          title: "Sere Nano 3x5m",
          price: 75000,
          rating: 4,
          description: "Sere nano për kopshte shtëpiake 3m x 5m, strukturë alumini, mbulesë polikarbonat 6mm, montim i shpejtë pa nevojë për themel.",
          mainImage: "/img/f/34.jpeg",
          slug: "sera-nano-demo",
          manufacturer: "UBT AgroMarket",
          category: "Serat",
          inStock: 1,
        },
        {
          id: "35",
          title: "Sere me Kontroll Klimatik",
          price: 4500000,
          rating: 5,
          description: "Sere me sistem të plotë kontrolli klimatik: temperaturë, lagështi, CO2 dhe dritë, përfshin sistem fogging, hijezim dhe ngrohje.",
          mainImage: "/img/f/35.jpg",
          slug: "sera-smart-demo",
          manufacturer: "UBT AgroMarket",
          category: "Serat",
          inStock: 1,
        },
        {
          id: "36",
          title: "Sere për Bime Medicinale",
          price: 2800000,
          rating: 4,
          description: "Sere speciale për bime medicinale me sistem filtimi të dritës, kontroll të saktë të mikroklimës dhe zonë të izoluar për ruajtje.",
          mainImage: "/img/f/36.jpg",
          slug: "sera-mjekesore-demo",
          manufacturer: "UBT AgroMarket",
          category: "Serat",
          inStock: 1,
        },
        {
          id: "37",
          title: "Sere Vertikale Hidroponike",
          price: 1250000,
          rating: 5,
          description: "Sere vertikale me sistem hidroponik të integruar, kapacitet 5000 bimë, përfshin sistem qarkullimi ujor dhe ndriçim LED.",
          mainImage: "/img/f/37.jpeg",
          slug: "sera-vertikale-demo",
          manufacturer: "UBT AgroMarket",
          category: "Serat",
          inStock: 1,
        },
        {
          id: "38",
          title: "Mini Sere",
          price: 3200000,
          rating: 4,
          description: "Sere premium me strukturë pa shtylla të brendshme për hapësirë maksimale",
          mainImage: "/img/f/38.jpg",
          slug: "sera-xhami-demo",
          manufacturer: "UBT AgroMarket",
          category: "Serat",
          inStock: 1,
        },
        {
          id: "39",
          title: "Sere për Shkurre Ushqimore",
          price: 1500000,
          rating: 4,
          description: "Sere e specializuar për rritje të shkurreve ushqimore (bluberry, etc.) me lartësi 4m dhe sistem kontrolli pH të tokës.",
          mainImage: "/img/f/39.jpg",
          slug: "sera-shkurre-demo",
          manufacturer: "UBT AgroMarket",
          category: "Serat",
          inStock: 1,
        },
        {
          id: "40",
          title: "Sere Mobil për Kërkime",
          price: 950000,
          rating: 5,
          description: "Sere mobil me modula të ndryshueshëm për qëllime kërkimore, përfshin sisteme monitorimi të të dhënave dhe ndarje të kontrolluara.",
          mainImage: "/img/f/40.jpg",
          slug: "sera-kerkimore-demo",
          manufacturer: "UBT AgroMarket",
          category: "Serat",
          inStock: 1,
        },
        {
          id: "41",
          title: "Sere me Energji Diellore",
          price: 3800000,
          rating: 5,
          description: "Sere e vetëqëndrueshme me panele diellore të integruara, sistem akumulimi energjie dhe automatizim të plotë pa lidhje me rrjetin.",
          mainImage: "/img/f/41.jpg",
          slug: "sera-diellore-demo",
          manufacturer: "UBT AgroMarket",
          category: "Serat",
          inStock: 1,
        },

          {
            id: "42",
            title: "Sistem Agrobot për Korrje të Automatizuar",
            price: 38000000,
            rating: 5,
            description: "Sistem robotik për korrje automatike të frutave dhe perimeve duke përdorur teknologji 3D vision dhe mësim makinerik për të identifikuar pjekurinë optimale.",
            mainImage: "/img/f/42.png",
            slug: "agrobot-demo",
            manufacturer: "Agrobot",
            category: "Teknologjia",
            inStock: 1,
          },
          {
            id: "43",
            title: "Dron Agras T30 për Fshirje",
            price: 2500000,
            rating: 4,
            description: "Dron profesional për fshirje me kapacitet 30kg, sistem i avancuar i spërkatjes dhe planifikimi i rrugës me GPS për saktësi maksimale.",
            mainImage: "/img/f/43.jpg",
            slug: "dron-fshirje-demo",
            manufacturer: "DJI",
            category: "Teknologjia",
            inStock: 1,
          },
          {
            id: "44",
            title: "Senzorë IoT për Monitorim të Tokës",
            price: 120000,
            rating: 4,
            description: "Sistem i plotë senzorësh IoT për monitorim në kohë reale të lagështisë së tokës, temperaturës, pH dhe niveleve të nutrienteve.",
            mainImage: "/img/f/44.jpg",
            slug: "sensor-toke-demo",
            manufacturer: "CropX",
            category: "Teknologjia",
            inStock: 1,
          },
          {
            id: "45",
            title: "Traktor Autonom Monarch",
            price: 15000000,
            rating: 5,
            description: "Traktor plotësisht autonom me energji elektrike, pajisur me sistem të avancuar vizionit dhe GPS RTK për saktësi centimetrik.",
            mainImage: "/img/f/45.png",
            slug: "traktor-autonom-demo",
            manufacturer: "Monarch Tractor",
            category: "Teknologjia",
            inStock: 1,
          },
          {
            id: "46",
            title: "Sistem Hidroponik Vertical Farm",
            price: 7500000,
            rating: 5,
            description: "Sistem i plotë hidroponik vertikal me kontroll klimatik, ndriçim LED të programueshëm dhe monitorim të automatizuar të nutrienteve.",
            mainImage: "/img/f/46.webp",
            slug: "farm-vertikale-demo",
            manufacturer: "AeroFarms",
            category: "Teknologjia",
            inStock: 1,
          },
          {
            id: "47",
            title: "Robot Weed-It për Eliminim të Barërave të Këqija",
            price: 9500000,
            rating: 4,
            description: "Robot autonom që identifikon dhe eliminon barërat e këqija duke përdorur teknologji AI dhe spërkatje me saktësi milimetrik.",
            mainImage: "/img/f/47.jpeg",
            slug: "robot-weed-demo",
            manufacturer: "Weed-It",
            category: "Teknologjia",
            inStock: 1,
          },
          {
            id: "48",
            title: "Sistem Aquaponik Smart Farm",
            price: 6500000,
            rating: 5,
            description: "Sistem i integruar aquaponik që kombinon rritjen e peshkut me prodhimin e bimëve, me kontroll të plotë automatizuar të parametrave.",
            mainImage: "/img/f/48.jpg",
            slug: "aquaponik-demo",
            manufacturer: "Nelson and Pade",
            category: "Teknologjia",
            inStock: 1,
          },
          {
            id: "49",
            title: "Kuti IoT për Bimët e Qumështorëve",
            price: 85000,
            rating: 4,
            description: "Pajisje IoT për monitorim të gjallesës së kafshëve, duke përfshirë shëndetin, aktivitetin dhe prodhimin e qumështit në kohë reale.",
            mainImage: "/img/f/49.png",
            slug: "iot-blegtori-demo",
            manufacturer: "Cowlar",
            category: "Teknologjia",
            inStock: 1,
          },
          {
            id: "50",
            title: "Sistem VR për Trajnime Bujqësore",
            price: 1500000,
            rating: 4,
            description: "Platformë trajnimi me Realitet Virtual për edukimin e bujqëve në teknika moderne të kultivimit dhe përdorimin e pajisjeve.",
            mainImage: "/img/f/50.jpeg",
            slug: "vr-bujqesi-demo",
            manufacturer: "FarmVR",
            category: "Teknologjia",
            inStock: 1,
          },
          {
            id: "51",
            title: "Sistem Blockchain për Gjurmim të Produkteve",
            price: 3200000,
            rating: 5,
            description: "Platformë blockchain për gjurmim të plotë të produkteve bujqësore nga ferma në tryezë, duke siguruar transparencë dhe origjinë të verifikuar.",
            mainImage: "/img/f/51.png",
            slug: "blockchain-food-demo",
            manufacturer: "Provenance",
            category: "Teknologjia",
            inStock: 1,
          },
          
            {
              id: "52",
              title: "Frigorifer Industrial 20ft",
              price: 6800000,
              rating: 5,
              description: "Frigorifer industrial me kapacitet 20ft, temperaturë e rregullueshme -25°C deri +15°C, sistem inverter për kursim energjie, i përshtatshëm për ruajtje të gjatë të produkteve bujqësore.",
              mainImage: "/img/f/52.jpg",
              slug: "frigo-industrial-demo",
              manufacturer: "Carrier",
              category: "Magazinimi",
              inStock: 1,
            },
            {
              id: "53",
              title: "Dhoma e Ftohtë për Fruta 100m³",
              price: 8500000,
              rating: 5,
              description: "Dhoma e ftohtë profesionale për fruta me kapacitet 100m³, sistem kontrolli të atmosferës së kontrolluar (CA), lagështi relative 85-95%, temperaturë +0.5°C deri +15°C.",
              mainImage: "/img/f/53.jpeg",
              slug: "dhoma-fruta-demo",
              manufacturer: "Ziehl-Abegg",
              category: "Magazinimi",
              inStock: 1,
            },
            {
              id: "54",
              title: "Tank i Ftohtë për Qumësht 5000L",
              price: 3200000,
              rating: 4,
              description: "Tank i ftohtë prej çeliku inox për ruajtje të qumështit, kapacitet 5000 litra, temperaturë +4°C, sistem pastrimi CIP (Clean-in-Place), pajisur me agitator.",
              mainImage: "/img/f/54.jpeg",
              slug: "tank-qumesht-demo",
              manufacturer: "Milkplan",
              category: "Magazinimi",
              inStock: 1,
            },
            {
              id: "55",
              title: "Kontainer i Ftohtë për Transport 40ft",
              price: 7500000,
              rating: 5,
              description: "Kontainer refrigerues 40ft për transport detar dhe tokësor, gamë temperaturë -30°C deri +30°C, sistem monitorimi me GPS dhe alarm.",
              mainImage: "/img/f/55.jpeg",
              slug: "kontainer-transport-demo",
              manufacturer: "Daikin",
              category: "Magazinimi",
              inStock: 1,
            },
            {
              id: "56",
              title: "Sistem Ruajtjeje me Vakuum për Drithëra",
              price: 4500000,
              rating: 4,
              description: "Sistem i avancuar i ruajtjes së drithërave me vakuum, kapacitet 50 ton, mbrojtje nga insektet dhe mykjet pa përdorur kimikate, ruajtje deri në 2 vjet pa humbje cilësie.",
              mainImage: "/img/f/56.jpg",
              slug: "ruajtje-vakuum-demo",
              manufacturer: "GrainPro",
              category: "Magazinimi",
              inStock: 1,
            },
            {
              id: "57",
              title: "Aktiv Depozitë për Plehra 30m³",
              price: 2800000,
              rating: 4,
              description: "Depozitë e ventiluar për ruajtje të plehrave organike, kapacitet 30m³, sistem kontrolli i lagështisë dhe temperaturës për ruajtje optimale.",
              mainImage: "/img/f/57.jpeg",
              slug: "depo-plehra-demo",
              manufacturer: "BVL",
              category: "Magazinimi",
              inStock: 1,
            },
            {
              id: "58",
              title: "Silos Metalik për Drithëra 100 ton",
              price: 6500000,
              rating: 5,
              description: "Silos metalik për ruajtje të drithërave me kapacitet 100 ton, sistem shkarkimi me ajër të kompresuar, rezistent ndaj lagështisë dhe insekteve.",
              mainImage: "/img/f/58.jpg",
              slug: "silos-drithi-demo",
              manufacturer: "Sukup",
              category: "Magazinimi",
              inStock: 1,
            },
            {
              id: "59",
              title: "Tunel i Ftohtë për Pjekje të Mishit",
              price: 12000000,
              rating: 5,
              description: "Tunel profesional i ftohtë për pjekje dhe ruajtje të mishit, kapacitet 5 ton/ditë, temperaturë +0°C deri +4°C, sistem higjienizimi me UV.",
              mainImage: "/img/f/59.webp",
              slug: "tunel-mish-demo",
              manufacturer: "Johnson Controls",
              category: "Magazinimi",
              inStock: 1,
            },
            {
              id: "60",
              title: "Sistem Ruajtjeje të Patates në Tokë",
              price: 3500000,
              rating: 4,
              description: "Sistem i specializuar për ruajtjen e patates në tokë me kontroll të temperaturës dhe lagështisë, kapacitet 20 ton, pa nevojë për ndërtim të veçantë.",
              mainImage: "/img/f/60.webp",
              slug: "ruajtje-patate-demo",
              manufacturer: "Horticulture",
              category: "Magazinimi",
              inStock: 1,
            },
            {
              id: "61",
              title: "Arkivë e Ftohtë për Farëra",
              price: 2800000,
              rating: 5,
              description: "Arkivë profesionale për ruajtje afatgjatë të farërave, temperaturë -10°C, lagështi relative 25%, kapacitet 5000 paketa, ruajtje deri në 10 vjet pa humbje të mbirjes.",
              mainImage: "/img/f/61.jpg",
              slug: "arkive-fara-demo",
              manufacturer: "Seed Storage",
              category: "Magazinimi",
              inStock: 1,
            },
            
              {
                id: "62",
                title: "Fara Domatesh Hybrid 'Sweet Cluster'",
                price: 1200,
                rating: 5,
                description: "Domate kokrrizore me rendiment të lartë, fruta të ëmbla 120-150g, pjekje e hershme (65 ditë), rezistente ndaj sëmundjeve. (Pako 50 copë)",
                mainImage: "/img/f/62.webp",
                slug: "fara-domatesh-demo",
                manufacturer: "UBT AgroMarket",
                category: "FaraPerime",
                inStock: 1,
              },
              {
                id: "63",
                title: "Fara Specash 'California Wonder'",
                price: 1000,
                rating: 4,
                description: "Speca të ëmbël, të kuq kur pjeken, 150-200g, formë kubike, shumë të shijshëm. (Pako 100 copë)",
                mainImage: "/img/f/63.png",
                slug: "fara-specash-demo",
                manufacturer: "UBT AgroMarket",
                category: "FaraPerime",
                inStock: 1,
              },
              {
                id: "64",
                title: "Fara Trangujsh 'Sugar Baby'",
                price: 1500,
                rating: 5,
                description: "Tranguj të vegjël (3-4kg), shumë të ëmbël, pjekje e hershme (75 ditë), lëkurë e hollë. (Pako 25 copë)",
                mainImage: "/img/f/64.jpeg",
                slug: "fara-trangujsh-demo",
                manufacturer: "UBT AgroMarket",
                category: "FaraPerime",
                inStock: 1,
              },
              {
                id: "65",
                title: "Fara Patatesh 'Spunta'",
                price: 1800,
                rating: 4,
                description: "Patate të gjata me cilësi të shkëlqyer gatimi, rendiment i lartë, rezistente ndaj sëmundjeve. (Pako 1kg)",
                mainImage: "/img/f/65.jpeg",
                slug: "fara-patatesh-demo",
                manufacturer: "UBT AgroMarket",
                category: "FaraPerime",
                inStock: 1,
              },
              {
                id: "66",
                title: "Fara Qepë 'Red Baron'",
                price: 900,
                rating: 4,
                description: "Qepë të kuqe me shije të fortë, ruhen mirë, formë të rrumbullakët, peshë 80-100g. (Pako 200 copë)",
                mainImage: "/img/f/66.jpg",
                slug: "fara-qepe-demo",
                manufacturer: "UBT AgroMarket",
                category: "FaraPerime",
                inStock: 1,
              },
              {
                id: "67",
                title: "Fara Sallate 'Iceberg'",
                price: 700,
                rating: 4,
                description: "Sallatë kokë e fortë, rezistente ndaj nxehtësisë, formë të rrumbullakët, peshë 500-800g. (Pako 500 copë)",
                mainImage: "/img/f/67.jpg",
                slug: "fara-sallate-demo",
                manufacturer: "UBT AgroMarket",
                category: "FaraPerime",
                inStock: 1,
              },
              {
                id: "68",
                title: "Fara Trangujsh 'Marketmore'",
                price: 1100,
                rating: 5,
                description: "Tranguj të gjatë 20-25cm, pa hidhërim, produktivitet i lartë, përshtatshëm për serra. (Pako 100 copë)",
                mainImage: "/img/f/68.jpg",
                slug: "fara-kungujsh-demo",
                manufacturer: "UBT AgroMarket",
                category: "FaraPerime",
                inStock: 1,
              },
              {
                id: "69",
                title: "Fara Lulelakrash 'Green Macareta'",
                price: 1400,
                rating: 4,
                description: "Lulelakra të dendura, të buta dhe të shijshme, diametri 15-20cm, rezistente ndaj të ftohtit. (Pako 50 copë)",
                mainImage: "/img/f/69.jpg",
                slug: "fara-lulelakrash-demo",
                manufacturer: "UBT AgroMarket",
                category: "FaraPerime",
                inStock: 1,
              },
              {
                id: "70",
                title: "Fara Fasule 'Blue Lake'",
                price: 800,
                rating: 5,
                description: "Fasule bishtajore, kokrra të gjelbra 15cm, shumë të shijshme, rendiment i lartë. (Pako 150 copë)",
                mainImage: "/img/f/70.jpg",
                slug: "fara-fasule-demo",
                manufacturer: "UBT AgroMarket",
                category: "FaraPerime",
                inStock: 1,
              },
    
                {
                  id: "71",
                  title: "NPK 15-15-15 + Microelemente 25kg",
                  price: 2800,
                  rating: 5,
                  description: "Pleh i përgjithshëm me formulë të balancuar 15-15-15, me shtesë mikroelementesh (B, Cu, Fe, Mn, Mo, Zn), i përshtatshëm për të gjitha kulturat.",
                  mainImage: "/img/f/71.jpg",
                  slug: "npk-balancuar-demo",
                  manufacturer: "Yara",
                  category: "PlehraKimike",
                  inStock: 1,
                },
                {
                  id: "72",
                  title: "UREA 46% N 50kg",
                  price: 3500,
                  rating: 4,
                  description: "Pleh me përmbajtje të lartë azoti (46%), i përshtatshëm për të gjitha fazat e rritjes, veçanërisht në fazën vegjetative.",
                  mainImage: "/img/f/72.jpeg",
                  slug: "urea-46-demo",
                  manufacturer: "EuroChem",
                  category: "PlehraKimike",
                  inStock: 1,
                },
                {
                  id: "73",
                  title: "DAP 18-46-0 50kg",
                  price: 4200,
                  rating: 5,
                  description: "Diamonium Phosphate me 18% N dhe 46% P₂O₅, pleh ideal për përdorim në themelim dhe për zhvillimin e rrënjëve.",
                  mainImage: "/img/f/73.webp",
                  slug: "dap-pleh-demo",
                  manufacturer: "OCP",
                  category: "PlehraKimike",
                  inStock: 1,
                },
                {
                  id: "74",
                  title: "Potassium Sulfate 50% K₂O 25kg",
                  price: 3800,
                  rating: 4,
                  description: "Pleh me kalium pa klor, i përshtatshëm për kulturat sensitive ndaj klorit si patatet, frutat dhe perimet.",
                  mainImage: "/img/f/74.jpeg",
                  slug: "kalium-sulfat-demo",
                  manufacturer: "K+S",
                  category: "PlehraKimike",
                  inStock: 1,
                },
                {
                  id: "75",
                  title: "Pleh për Agrume 8-12-24+3MgO 25kg",
                  price: 3200,
                  rating: 5,
                  description: "Formulë e specializuar për agrume me përmbajtje të lartë kaliumi dhe magnez, përmirëson cilësinë e frutave.",
                  mainImage: "/img/f/75.png",
                  slug: "pleh-agrume-demo",
                  manufacturer: "Compo Expert",
                  category: "PlehraKimike",
                  inStock: 1,
                },
                {
                  id: "76",
                  title: "Pleh për Perime 12-10-18+6CaO 20kg",
                  price: 3000,
                  rating: 4,
                  description: "Formulë e balancuar për perime me shtesë kalciumi, përmirëson cilësinë dhe ruajtjen e produkteve.",
                  mainImage: "/img/f/76.jpeg",
                  slug: "pleh-perime-demo",
                  manufacturer: "Haifa",
                  category: "PlehraKimike",
                  inStock: 1,
                },
                {
                  id: "77",
                  title: "Pleh Granular për Patate 6-12-36 25kg",
                  price: 3400,
                  rating: 5,
                  description: "Formulë e specializuar për patate me përmbajtje të lartë kaliumi, rrit rendimentin dhe cilësinë e patates.",
                  mainImage: "/img/f/77.webp",
                  slug: "pleh-patate-demo",
                  manufacturer: "ICL",
                  category: "PlehraKimike",
                  inStock:  1,
                },
                {
                  id: "78",
                  title: "Pleh me Çlirim të Ngadaltë 18-5-10+2MgO 25kg",
                  price: 4500,
                  rating: 5,
                  description: "Pleh me teknologji çlirimi të ngadaltë, furnizon bimët me lëndë ushqyese për 3-4 muaj, redukton humbjet.",
                  mainImage: "/img/f/78.png",
                  slug: "pleh-ngadalte-demo",
                  manufacturer: "Florissa",
                  category: "PlehraKimike",
                  inStock: 1,
                },
                {
                  id: "79",
                  title: "Pleh Mikro Granular 10-40-10+ME 5kg",
                  price: 1800,
                  rating: 4,
                  description: "Pleh me përmbajtje të lartë fosfori dhe mikroelemente, ideal për përdorim në transplantim dhe në fazën e fillimit.",
                  mainImage: "/img/f/79.png",
                  slug: "pleh-mikro-demo",
                  manufacturer: "Agromaster",
                  category: "PlehraKimike",
                  inStock: 1,
                },
                {
                  id: "80",
                  title: "Pleh Lëngshëm 20-20-20+ME 10L",
                  price: 2800,
                  rating: 5,
                  description: "Pleh i plotë i tretshëm në ujë, me balancë perfekte NPK dhe mikroelemente, i përshtatshëm për aplikim në gjethe dhe në tokë.",
                  mainImage: "/img/f/80.jpeg",
                  slug: "pleh-lengshem-demo",
                  manufacturer: "NutriChem",
                  category: "PlehraKimike",
                  inStock: 1,
                },
                  {
                    id: "81",
                    title: "Fungicid Sistematik - Amistar Xtra",
                    price: 4500,
                    rating: 5,
                    description: "Fungicid i fuqishëm sistematik me azoxystrobin dhe cyproconazole, efektiv kundër sëmundjeve të gjetheve në grurë, misër dhe perime.",
                    mainImage: "/img/f/81.jpeg",
                    slug: "fungicid-amistar-demo",
                    manufacturer: "Syngenta",
                    category: "Pesticidet",
                    inStock: 1,
                  },
                  {
                    id: "82",
                    title: "Insekticid Kontakt - Actara 25WG",
                    price: 3800,
                    rating: 4,
                    description: "Insekticid sistematik me thiamethoxam, efektiv kundër afideve, breshkave të bardha dhe krimbave të tokës në perime dhe fruta.",
                    mainImage: "/img/f/82.jpeg",
                    slug: "insekticid-actara-demo",
                    manufacturer: "Syngenta",
                    category: "Pesticidet",
                    inStock: 1, 
                  },
                  {
                    id: "83",
                    title: "Herbicid Sistematik - Touchdown Forte",
                    price: 3200,
                    rating: 5,
                    description: "Herbicid jo-selektiv me glifosat, eliminon të gjitha barërat e këqija njëvjeçare dhe shumëvjeçare, i përshtatshëm për përdorim para mbjelljes.",
                    mainImage: "/img/f/83.jpeg",
                    slug: "herbicid-touchdown-demo",
                    manufacturer: "Syngenta",
                    category: "Pesticidet",
                    inStock: 1,
                  },
                  {
                    id: "84",
                    title: "Fungicid Kontakt - Dithane M45",
                    price: 2800,
                    rating: 4,
                    description: "Fungicid kontakt me mancozeb, mbrojtje e gjerë kundër sëmundjeve të ndryshme në perime, fruta dhe drithëra.",
                    mainImage: "/img/f/84.jpeg",
                    slug: "fungicid-dithane-demo",
                    manufacturer: "UPL",
                    category: "Pesticidet",
                    inStock: 1,
                  },
                  {
                    id: "85",
                    title: "Insekticid Pyrethroid - Decis 2.5EC",
                    price: 3000,
                    rating: 5,
                    description: "Insekticid kontakt me deltamethrin, efektiv kundër një game të gjerë insektesh të dëmshme në të gjitha kulturat bujqësore.",
                    mainImage: "/img/f/85.png",
                    slug: "insekticid-decis-demo",
                    manufacturer: "Bayer",
                    category: "Pesticidet",
                    inStock: 1,
                  },
                  {
                    id: "86",
                    title: "Herbicid Selektiv - Lontrel 300SL",
                    price: 4200,
                    rating: 4,
                    description: "Herbicid selektiv me clopyralid, kontrollon barërat e këqija gjerëfoliare në grurë, elb dhe misër pa dëmtuar kulturën.",
                    mainImage: "/img/f/86.jpg",
                    slug: "herbicid-lontrel-demo",
                    manufacturer: "Dow AgroSciences",
                    category: "Pesticidet",
                    inStock: 1,
                  },
                  {
                    id: "87",
                    title: "Fungicid Sistematik - Tilt 250EC",
                    price: 3600,
                    rating: 5,
                    description: "Fungicid sistematik me propiconazole, efektiv kundër mykut, ndryshkut dhe sëmundjeve të tjera të gjetheve në drithëra dhe fruta.",
                    mainImage: "/img/f/87.jpeg",
                    slug: "fungicid-tilt-demo",
                    manufacturer: "Syngenta",
                    category: "Pesticidet",
                    inStock: 1,
                  },
                  {
                    id: "88",
                    title: "Insekticid Sistematik - Confidor 200SL",
                    price: 4000,
                    rating: 5,
                    description: "Insekticid sistematik me imidacloprid, kontrollon afidet, breshkën e bardhë dhe thripsat në perime, fruta dhe lule.",
                    mainImage: "/img/f/88.jpg",
                    slug: "insekticid-confidor-demo",
                    manufacturer: "Bayer",
                    category: "Pesticidet",
                    inStock: 1,
                  },
                  {
                    id: "89",
                    title: "Herbicid Pre-Emergjent - Stomp 330EC",
                    price: 3400,
                    rating: 4,
                    description: "Herbicid pre-emergjent me pendimethalin, parandalon mbirjen e barërave të këqija njëvjeçare në perime dhe drithëra.",
                    mainImage: "/img/f/89.png",
                    slug: "herbicid-stomp-demo",
                    manufacturer: "BASF",
                    category: "Pesticidet",
                    inStock: 1,
                  },
                  {
                    id: "90",
                    title: "Fungicid Kontakt - Copper Oxychloride 50WP",
                    price: 2500,
                    rating: 4,
                    description: "Fungicid kontakt me bakër, përdoret për parandalimin dhe kontrollin e sëmundjeve të ndryshme mykotike në të gjitha kulturat.",
                    mainImage: "/img/f/90.jpg",
                    slug: "fungicid-copper-demo",
                    manufacturer: "UPL",
                    category: "Pesticidet",
                    inStock: 1,
                  },
                
                    {
                      id: "91",
                      title: "Sistem Ujitje me Pikë DripNet PC",
                      price: 45000,
                      rating: 5,
                      description: "Sistem profesional ujitjeje me pikë për serra dhe kopshte, presion pune 1-3 bar, rrjedhë 1.6L/h, i përshtatshëm për të gjitha llojet e bimëve.",
                      mainImage: "/img/f/91.jpeg",
                      slug: "sistem-dripnet-demo",
                      manufacturer: "Netafim",
                      category: "Ujitje",
                      inStock: 1,
                    },
                    {
                      id: "92",
                      title: "Pompë Nëndetëse 5HP",
                      price: 62000,
                      rating: 4,
                      description: "Pompë nëndetëse 5HP për puset, thellësi maksimale 80m, kapacitet 8m³/h, e përshtatshme për sistemet e ujitjes me presion të lartë.",
                      mainImage: "/img/f/92.jpg",
                      slug: "pompe-nendetese-demo",
                      manufacturer: "Grundfos",
                      category: "Ujitje",
                      inStock: 1,
                    },
                    {
                      id: "93",
                      title: "Pajisje Ujitjeje me Rrotullim 360°",
                      price: 38000,
                      rating: 5,
                      description: "Pajisje ujitjeje me rrotullim të plotë, rreze 15-25m, i përshtatshëm për kopshte dhe fusha të vogla, konsum i ulët uji.",
                      mainImage: "/img/f/93.jpg",
                      slug: "pajisje-rotulluese-demo",
                      manufacturer: "Rain Bird",
                      category: "Ujitje",
                      inStock: 1,
                    },
                    {
                      id: "94",
                      title: "Valvulë Automatike për Ujitje",
                      price: 8500,
                      rating: 4,
                      description: "Valvulë automatike 24V për sistemet e ujitjes, presion pune 1-10 bar, e përshtatshme për përdorim në tokë dhe në serra.",
                      mainImage: "/img/f/94.jpg",
                      slug: "valvule-automatike-demo",
                      manufacturer: "Hunter",
                      category: "Ujitje",
                      inStock: 1,
                    },
                    {
                      id: "95",
                      title: "Filtër Disk për Ujitje me Pikë",
                      price: 12000,
                      rating: 5,
                      description: "Filtër disk 120 mesh për sistemet e ujitjes me pikë, kapacitet 10m³/h, lehtë për pastrim dhe mirëmbajtje.",
                      mainImage: "/img/f/95.jpeg",
                      slug: "filter-disk-demo",
                      manufacturer: "Azud",
                      category: "Ujitje",
                      inStock: 1,
                    },
                    {
                      id: "96",
                      title: "Kontrollor Ujitjeje me 8 Zona",
                      price: 22000,
                      rating: 4,
                      description: "Kontrollor profesional për sistemet e ujitjes me 8 zona të pavarura, programim të lehtë, rezistent ndaj reshjeve dhe ndikimeve të jashtme.",
                      mainImage: "/img/f/96.webp",
                      slug: "kontrollor-8-zone-demo",
                      manufacturer: "Orbit",
                      category: "Ujitje",
                      inStock: 1,
                    },
                    {
                      id: "97",
                      title: "Tub Polietileni për Ujitje 25mm",
                      price: 850,
                      rating: 4,
                      description: "Tub polietileni 25mm (LDPE) për sistemet e ujitjes, presion pune 4 bar, rezistent ndaj UV dhe kimikateve, në metër linear.",
                      mainImage: "/img/f/97.jpeg",
                      slug: "tub-polietileni-demo",
                      manufacturer: "Eurodrip",
                      category: "Ujitje",
                      inStock: 1,
                    },
                    {
                      id: "98",
                      title: "Pistole Ujitjeje Profesionale",
                      price: 4500,
                      rating: 5,
                      description: "Pistolë ujitjeje profesionale me 8 mënyra, rrymë e rregullueshme, ergonomike dhe e qëndrueshme për përdorim të përditshëm.",
                      mainImage: "/img/f/98.jpg",
                      slug: "pistole-profesionale-demo",
                      manufacturer: "Gardena",
                      category: "Ujitje",
                      inStock: 1,
                    },
                    {
                      id: "99",
                      title: "Sistem Ujitjeje me Mjegull për Serra",
                      price: 125000,
                      rating: 5,
                      description: "Sistem i avancuar ujitjeje me mjegull për serra, kontroll i saktë i lagështisë dhe temperaturës, i përshtatshëm për bimë të ndjeshme.",
                      mainImage: "/img/f/99.jpg",
                      slug: "mjegull-sera-demo",
                      manufacturer: "Nova Fert",
                      category: "Ujitje",
                      inStock: 1,
                    },
                      {
                        id: "101",
                        title: "Pantalona Bujqësore me Mbrojtës",
                        price: 4500,
                        rating: 4,
                        description: "Pantalona të qëndrueshme për punë në fermë me pëlhurë rezistente, mbrojtës të integruar për gjunjët dhe shumë xhepa për vegla.",
                        mainImage: "/img/f/101.jpg",
                        slug: "pantalona-bujqesore-demo",
                        manufacturer: "Dickies",
                        category: "Veshje",
                        inStock: 1,
                      },
                      {
                        id: "102",
                        title: "Xhaketë e Punës me Reflektues",
                        price: 6500,
                        rating: 5,
                        description: "Xhaketë e punës me shirita reflektues për punë natën, rezistente ndaj ujit dhe erërave, me multiple xhepa funksionale.",
                        mainImage: "/img/f/102.jpeg",
                        slug: "xhakete-reflektuese-demo",
                        manufacturer: "Carhartt",
                        category: "Veshje",
                        inStock: 1,
                      },
                      {
                        id: "103",
                        title: "Çizme Gome për Bujqësi",
                        price: 3200,
                        rating: 4,
                        description: "Çizme të shkurtra gomike për punë në fermë, lehtë për t'u veshur dhe hequr, rezistente ndaj kimikateve dhe vajrave.",
                        mainImage: "/img/f/103.jpeg",
                        slug: "cizme-gome-demo",
                        manufacturer: "Muck Boot",
                        category: "Veshje",
                        inStock: 1,
                      },
                      {
                        id: "104",
                        title: "Dorashka Punë me Grip",
                        price: 1200,
                        rating: 4,
                        description: "Dorashka të qëndrueshme për punë me grip të mirë, mbrojtje kundër prerjeve dhe fërkimeve, material i thithshëm.",
                        mainImage: "/img/f/104.jpeg",
                        slug: "dorashka-pune-demo",
                        manufacturer: "Mechanix",
                        category: "Veshje",
                        inStock: 1,
                      },
                      {
                        id: "105",
                        title: "Kapelë Bujqësore me Hije",
                        price: 1800,
                        rating: 4,
                        description: "Kapelë me hije të gjerë për mbrojtje nga dielli, material i lehtë dhe i ajrosur, rrip chin strap për të parandaluar hedhjen nga era.",
                        mainImage: "/img/f/105.jpeg",
                        slug: "kapele-bujqesore-demo",
                        manufacturer: "Tilley",
                        category: "Veshje",
                        inStock: 1,
                      },
                      {
                        id: "106",
                        title: "Veshje Mbrojtëse për Përdorim të Pesticideve",
                        price: 8500,
                        rating: 5,
                        description: "Veshje e plotë e papërshkueshme për mbrojtje gjatë përdorimit të pesticideve, me kapuç dhe rreshtim të ventiluar.",
                        mainImage: "/img/f/106.jpeg",
                        slug: "veshje-pesticide-demo",
                        manufacturer: "DuPont",
                        category: "Veshje",
                        inStock: 1,
                      },
                      {
                        id: "107",
                        title: "Fustan Bujqësor me Mbrojtës Dielli",
                        price: 2800,
                        rating: 4,
                        description: "Fustan i lehtë bujqësor me mbrojtje UV 50+, material i ajrosur dhe i thithshëm, i përshtatshëm për mot të nxehtë.",
                        mainImage: "/img/f/107.jpg",
                        slug: "fustan-bujqesor-demo",
                        manufacturer: "Columbia",
                        category: "Veshje",
                        inStock: 1,
                      },
                      {
                        id: "108",
                        title: "Shami për Qafë me Mbrojtje UV",
                        price: 800,
                        rating: 4,
                        description: "Shami e shumëfunkshme për qafë me mbrojtje nga dielli, mund të përdoret edhe si maskë kundër pluhurit.",
                        mainImage: "/img/f/108.jpg",
                        slug: "shami-qafe-demo",
                        manufacturer: "Buff",
                        category: "Veshje",
                        inStock: 1,
                      },
                      {
                        id: "109",
                        title: "Veshje Termike për Dimër",
                        price: 5500,
                        rating: 5,
                        description: "Veshje e ngrohtë për punë në temperatura të ulëta, rezistente ndaj erërave dhe lagështirës, me shtresa të ajrosura.",
                        mainImage: "/img/f/109.jpg",
                        slug: "veshje-termike-demo",
                        manufacturer: "Helly Hansen",
                        category: "Veshje",
                        inStock: 1,
                      },
                      {
                        id: "110",
                        title: "Këpucë Sigurie për Fermë",
                        price: 7500,
                        rating: 4,
                        description: "Këpucë sigurie me majë çeliku dhe shul rezistent ndaj vajrave, të rehatshme për përdorim të gjatë në këmbë.",
                        mainImage: "/img/f/110.jpeg",
                        slug: "kepuce-sigurie-demo",
                        manufacturer: "Timberland PRO",
                        category: "Veshje",
                        inStock: 1,
                      }              

];

async function insertDemoData() {
  try {
    // Clear existing data (optional)
    await prisma.$transaction([
      prisma.customer_order_product.deleteMany(),
      prisma.customer_order.deleteMany(),
      prisma.wishlist.deleteMany(),
      prisma.product.deleteMany(),
      prisma.category.deleteMany(),
    ]);

    // Insert categories first with explicit IDs
    console.log("Inserting demo categories...");
    await prisma.category.createMany({
      data: demoCategories,
      skipDuplicates: true
    });

    // Create a map of category names to IDs
    const categoryMap = {};
    demoCategories.forEach(cat => {
      categoryMap[cat.name] = cat.id;
    });

    // Insert products with proper category relationships
    console.log("Inserting demo products...");
    await Promise.all(
      demoProducts.map(product => {
        const categoryId = categoryMap[product.category];
        
        if (!categoryId) {
          console.warn(`Category "${product.category}" not found for product "${product.title}"`);
          return null;
        }

        return prisma.product.upsert({
          where: { id: product.id },
          update: {},
          create: {
            id: product.id,
            title: product.title,
            price: product.price,
            rating: product.rating,
            description: product.description,
            mainImage: product.mainImage,
            slug: product.slug,
            manufacturer: product.manufacturer,
            inStock: product.inStock,
            categoryId: categoryId
          }
        });
      }).filter(Boolean)
    );

    console.log("Demo data inserted successfully!");
  } catch (error) {
    console.error("Error inserting demo data:", error);
  } finally {
    await prisma.$disconnect();
  }
}

insertDemoData();